base: 'http://codeexamples.ddev.site/'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de-DE
    direction: ''
    flag: de
  -
    title: English
    enabled: true
    base: /en/
    locale: en_GB.UTF-8
    iso-639-1: en
    typo3Language: default
    websiteTitle: ''
    navigationTitle: EN
    hreflang: en-gb
    fallbackType: free
    fallbacks: ''
    direction: ''
    flag: gb
    languageId: 1
rootPageId: 1
websiteTitle: 'Codeexamples'
