inheritDefault: true
mutations:
  - mode: set
    directive: 'default-src'
    sources:
      - "'self'"

  - mode: extend
    directive: 'img-src'
    sources:
      - 'data:'
      - 'http://*.example-13.ddev.site/'

  - mode: extend
    directive: 'font-src'
    sources:
      - 'fonts.gstatic.com'
      - 'fonts.googleapis.com'
